### ISSUE TITLE
[bug] TypeError: Cannot read properties of undefined (reading 'name')

### ISSUE THREAD

**Issue by codebydant** [SvanBoxel/azure-cost-report-action#15]
Hi @SvanBoxel

I am getting an error when running locally and in the github runner.

## Locally

```bash
subscriptionId directoryId clientId=clientSecret= node src/index.js

/home/daniel/Downloads/azure-cost-report-action/src/index.js:123
    finishedPeriods[0].name,
                       ^

TypeError: Cannot read properties of undefined (reading 'name')
    at run (/home/daniel/Downloads/azure-cost-report-action/src/index.js:123:24)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

Node.js v18.16.0

```

## Github
```bash
Run SvanBoxel/azure-cost-report-action@0.2.0
(node:1734) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'name' of undefined
    at run (/home/runner/work/_actions/SvanBoxel/azure-cost-report-action/0.2.0/dist/index.js:110409:24)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
(node:1734) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:1734) [DEP001[8](https://github.com/org/repo/actions/runs/5213618041/jobs/9408844349#step:3:9)] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by codebydant** [comment]
Closing this since I am using https://github.com/mivano/azure-cost-cli
